### ISSUE TITLE
浏览器无法连接到 noVNC 监听端口

### ISSUE THREAD

**Issue by xyx0826** [CoolQ/docker-wine-coolq#10]
Docker 容器启动命令行：
```docker run --rm -p [服务器 IPv4]:9001:9001 -v `pwd`:/home/user/coolq coolq/wine-coolq```

> 编辑：命令行实使用了 `9001` 端口，因 `9000` 已被占用。

服务器日志：
```
WebSocket server settings:
  - Listen on :9001
  - No SSL/TLS support (no cert file)
  - proxying from :9001 to 127.0.0.1:5911

New '3b69a7610d0f:11 (user)' desktop is 3b69a7610d0f:11

Creating default startup script /home/user/.vnc/xstartup
Creating default config /home/user/.vnc/config
Starting applications specified in /home/user/.vnc/xstartup
Log file is /home/user/.vnc/3b69a7610d0f:11.log

[CQDaemon] Starting CoolQ ....
[CQDaemon] Started CoolQ .
144.***.**.** - - [26/Jul/2018 13:46:03] code 405, message Method Not Allowed
```
但是使用 Chrome 访问 `[服务器 IPv4]:9001` 时却报出错误：
```
Error response
Error code 405.

Message: Method Not Allowed.

Error code explanation: 405 = Specified method is invalid for this resource..
```
个人猜想：noVNC 是不是在监听 WebSocket? https://github.com/novnc/websockify/issues/248 提到需要用 `--web` 参数来允许 HTTP 连接。

**Comment by oott123** [comment]
你不需要访问 9001 端口，而应当访问 9000 端口。请仔细阅读文档。

**Comment by xyx0826** [comment]
不好意思，我随后编辑了 Issue, 增添了说明。
用 `9001` 端口是因为 `9000` 已被服务器上的其他应用占用。
必须使用 `9000` 才能解决这个问题吗？

**Comment by oott123** [comment]
你的用法是错误的。请参考 docker 的文档。

**Comment by oott123** [comment]
更具体一些：你把容器的 9001 端口转发到的服务器的 9001 端口。这是错误的。

如果你不希望使用服务器的 9000 端口，你应该把其它端口转发到容器的 9000 上，而非 9001。

更具体一些：两个 9001 中的一个需要改成 9000 才会如你预期。

**Comment by xyx0826** [comment]
感谢点拨。使用以下的命令行启动成功：
`··docker run --rm -p [服务器 IPv4]:9001:9000 -v `pwd`:/home/user/coolq coolq/wine-coolq`··
