### ISSUE TITLE
请教应用加载的问题

### ISSUE THREAD

**Issue by Sciroccogti** [CoolQ/docker-wine-coolq#14]
我在`~/coolq/app`下放置了新的cqk文件，但是在实例运行的**应用目录**内却无法显示。

据查出现了这样的问题：
*  我认为的路径：`/home/ubuntu/coolq`
*  **应用目录**中显示的路径：`/home/user/coolq`，但事实上却并没有`user`文件夹
*  使用**应用目录**查看路径，存在`ubuntu`文件夹，但是里面的`coolq`文件夹是空的，`user`文件夹却与`ubuntu`一致

以上冲突导致我无法增加应用

**Comment by oott123** [comment]
Learn to use docker first please.

https://docs.docker.com/storage/volumes/
