### ISSUE TITLE
Docker把硬盘搞满了，怎么解决啊

### ISSUE THREAD

**Issue by yh371174229** [CoolQ/docker-wine-coolq#15]
![image](https://user-images.githubusercontent.com/5948456/52942313-bae98f80-33a5-11e9-9985-9bfe21037c65.png)

**Comment by oott123** [comment]
首先，这是 overlay fs。
其次，工具使用/服务器运维问题，与本项目无关，请去寻求对应的技术支持。

**Comment by yh371174229** [comment]
我还以为是酷q产生的临时文件太多了，多有打扰。
