### ISSUE TITLE
大佬能做个Amanda的docker么?

### ISSUE THREAD

**Issue by TwilightHome** [CoolQ/docker-wine-coolq#2]
Amanda机器人目前支持图片收发...想做docker,不会...

**Comment by Coxxs** [comment]
Hi，感谢关注！我们目前没有此类计划。

**Comment by oott123** [comment]
😄 你可能需要问问 Amanda 有没有制作 docker 容器的计划。于我个人而言，我是酷Q Pro 用户，没有此类需求；于团队而言，我也不适合干这事~~
