### ISSUE TITLE
很抱歉，无法连接服务器。

### ISSUE THREAD

**Issue by adin283** [CoolQ/docker-wine-coolq#21]
noVNC 连接后，输完授权码就报错了
很抱歉，无法连接服务器。请检查网络连接是否畅通并重试！(CA999)

环境:
macos 10.14.4
docker 2.0.0.3 for mac

docker 命令如下：
docker run --name coolq \
-p 9000:9000 \
-v /Users/me/coolq:/home/user/coolq \
-e VNC_PASSWD=123456 \
-e COOLQ_ACCOUNT=my bind qq \
-e COOLQ_URL=http://dlsec.cqp.me/cqp-tuling \
coolq/wine-coolq

**Comment by Coxxs** [comment]
请检查网络是否正常，相关问题不建议在这里提出
