### ISSUE TITLE
提了issue没解决就给我关闭了？还直接删除了？我买了pro就是这也的服务？你们论坛我提了还要审核问题都没出现！

### ISSUE THREAD

**Issue by adin283** [CoolQ/docker-wine-coolq#22]
提了issue没解决就给我关闭了？还直接删除了？我买了pro就是这样的服务？
你们论坛我提了还要审核问题都没出现！只能这里提了！！！issue 21 望解决！

“请检查网络是否正常，相关问题不建议在这里提出” 这么敷衍的回答是做技术的人回答的吗？网络我肯定检查了没有问题啊。相关问题不建议在这里提出？？？我去论坛题问题都要审核出现不了！

**Comment by Coxxs** [comment]
这里是 **docker-wine-coolq**，请不要在这里提不相关问题，更不要反复提出非相关问题。
