### ISSUE TITLE
连接不了下载CoolQ的网站

### ISSUE THREAD

**Issue by 691778949** [CoolQ/docker-wine-coolq#23]
正在连接 dlsec.cqp.me (dlsec.cqp.me)|117.34.14.64|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 404 
2019-05-13 16:50:16 错误 404：(没有描述)。

**Comment by oott123** [comment]
有指定 `COOLQ_URL` 环境变量吗？

**Comment by 691778949** [comment]
怎么制定呀

**Comment by oott123** [comment]
那就是没有指定。我觉得可能是你 docker 镜像哪儿有点问题，不然删了重新来试试？

**Comment by 691778949** [comment]
我试过了重新下载镜像，但是没用，本地可以成功，百度云服务器报上面的错误

**Comment by oott123** [comment]
在服务器上运行：

```bash
wget -O /dev/null http://dlsec.cqp.me/cqa-tuling
```

把结果贴上来看一下

**Comment by 691778949** [comment]
--2019-05-13 18:31:18--  http://dlsec.cqp.me/cqa-tuling
Resolving dlsec.cqp.me (dlsec.cqp.me)... 117.34.14.64
Connecting to dlsec.cqp.me (dlsec.cqp.me)|117.34.14.64|:80... connected.
HTTP request sent, awaiting response... 302 Found
Cookie coming from dlsec.cqp.me attempted to set domain to cqp.me
Location: //dlcq.cqp.me/cq/CQA-tuling.zip [following]
--2019-05-13 18:31:18--  http://dlcq.cqp.me/cq/CQA-tuling.zip
Resolving dlcq.cqp.me (dlcq.cqp.me)... 117.34.14.64
Reusing existing connection to dlsec.cqp.me:80.
HTTP request sent, awaiting response... 200 OK
Cookie coming from dlcq.cqp.me attempted to set domain to cqp.me
Length: 1168567 (1.1M) [application/zip]
Saving to: ‘/dev/null’

/dev/null           100%[===================>]   1.11M  --.-KB/s    in 0.1s    

2019-05-13 18:31:19 (7.60 MB/s) - ‘/dev/null’ saved [1168567/1168567]


这个是可以的

**Comment by 691778949** [comment]
我又试了一下 docker run --rm -p 9000:9000 -v `pwd`:/home/user/coolq coolq/wine-coolq  
还是这样

Downloading CoolQ ...
--2019-05-13 18:35:47--  http://dlsec.cqp.me/cqa-tuling
正在解析主机 dlsec.cqp.me (dlsec.cqp.me)... 117.34.14.64
正在连接 dlsec.cqp.me (dlsec.cqp.me)|117.34.14.64|:80... 失败：拒绝连接。
Unzipping CoolQ ...
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of coolq.zip or
        coolq.zip.zip, and cannot find coolq.zip.ZIP, period.
mv: 无法获取'*/*' 的文件状态(stat): 没有那个文件或目录

**Comment by oott123** [comment]
这就很奇怪了。请你运行：
```bash
docker run --rm -e DEBUG=1 coolq/wine-coolq
```
再把输出贴上来看看。

**Comment by 691778949** [comment]
[cont-init.d] 110-get-coolq: executing... 
Downloading CoolQ ...
--2019-05-13 18:39:50--  http://dlsec.cqp.me/cqa-tuling
正在解析主机 dlsec.cqp.me (dlsec.cqp.me)... 117.34.14.64
正在连接 dlsec.cqp.me (dlsec.cqp.me)|117.34.14.64|:80... 失败：拒绝连接。
Unzipping CoolQ ...
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of coolq.zip or
        coolq.zip.zip, and cannot find coolq.zip.ZIP, period.
mv: 无法获取'*/*' 的文件状态(stat): 没有那个文件或目录
[cont-init.d] 110-get-coolq: exited 0.

**Comment by 691778949** [comment]
还是这样

**Comment by oott123** [comment]
不知道为啥，这还是挺奇怪的。不如干脆手动下载吧。服务器上执行：

```bash
DIR=$(pwd)
wget http://dlsec.cqp.me/cqa-tuling -O /tmp/cq/coolq.zip
cd /tmp/cq
LC_ALL=zh_CN.UTF-8 unzip coolq.zip > /dev/null
chmod -R 777 .
mv */* "$DIR"
cd "$DIR"
rm -rf /tmp/cq
```

可以手动把酷Q下载到当前目录。再运行：

```bash
docker run --rm -p 9000:9000 -v `pwd`:/home/user/coolq coolq/wine-coolq
```

的时候就不会重新下载了。

**Comment by 691778949** [comment]
好的大佬，我试一下

**Comment by 691778949** [comment]
出现了新问题
![QQ图片20190513185634](https://user-images.githubusercontent.com/37395171/57616507-ddf49b80-75b0-11e9-87a8-2fbff4ad45e1.png)

**Comment by 691778949** [comment]
是百度云服务器阻断了CoolQ的连接吗

**Comment by oott123** [comment]
我感觉你的 docker 连不上网，不管是下载酷Q还是连接酷Q服务器。

请你运行：

```bash
docker run --rm coolq/wine-coolq curl myip.ipip.net
```

看看容器内能不能正常上网。

**Comment by 691778949** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 010-app: applying... 
[fix-attrs.d] 010-app: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 010-setup-vnc: executing... 
Would you like to enter a view-only password (y/n)? Password:Verify:[cont-init.d] 010-setup-vnc: exited 0.
[cont-init.d] 020-setup-sudo: executing... 
[cont-init.d] 020-setup-sudo: exited 0.
[cont-init.d] 110-get-coolq: executing... 
Downloading CoolQ ...
--2019-05-13 19:01:28--  http://dlsec.cqp.me/cqa-tuling
正在解析主机 dlsec.cqp.me (dlsec.cqp.me)... 117.34.14.64
正在连接 dlsec.cqp.me (dlsec.cqp.me)|117.34.14.64|:80... 失败：拒绝连接。
Unzipping CoolQ ...
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of coolq.zip or
        coolq.zip.zip, and cannot find coolq.zip.ZIP, period.
mv: 无法获取'*/*' 的文件状态(stat): 没有那个文件或目录
[cont-init.d] 110-get-coolq: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to myip.ipip.net port 80: 拒绝连接
/sbin/entrypoint.sh exited 7
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by 691778949** [comment]
好像是的

**Comment by oott123** [comment]
连不上网那就没办法啦。

也许你需要检查下 docker 的设置，或者重装一下服务器，装成 Ubuntu 啥的，可能比较容易？听起来不是我能帮你解决的问题，先 close 啦。

**Comment by 691778949** [comment]
好的，谢谢你
