### ISSUE TITLE
arm的linux设备 树莓派  n1无法运行镜像  报错：standard_init_linux.go:190: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by summmer121** [CoolQ/docker-wine-coolq#24]
报错：standard_init_linux.go:190: exec user process caused "exec format error"

**Comment by oott123** [comment]
本镜像仅支持 x86 和 x86_64 平台。

**Comment by RealKiro** [comment]
> 本镜像仅支持 x86 和 x86_64 平台。

![image](https://user-images.githubusercontent.com/33367701/77041534-092bf080-69f5-11ea-8bbb-36d6c42b97e1.png)

其实硬路由现在也可以玩Docker了，能适配arm/mtk...嘛（小声

**Comment by oott123** [comment]
@RealKiro wine [难以](https://wiki.winehq.org/ARM)在 arm 平台上运行、无法在 mtk 平台上运行。此外，酷Q 也难以在 arm 平台上运行，需要[模拟](https://wiki.winehq.org/Emulation)。如果你愿意解决这些问题，可以尝试适配。
