### ISSUE TITLE
docker关于qq图片保存失败(权限问题?)

### ISSUE THREAD

**Issue by airflybusoren** [CoolQ/docker-wine-coolq#27]
如题,具体说一下情况,就是上传后ok了

但实质上文件只有1k,不知是不是linux权限问题,还是下载本身就出现问题
排除了插件问题
使用的是https://github.com/kotoneme/docker-wine-coolq-dotnet45提供的docker镜像,
同使用论坛的docker也一样有这种情况
版本显示酷q5.14版本

**Comment by oott123** [comment]
听起来是酷Q问题，建议去酷Q论坛问问
