### ISSUE TITLE
汉字编码以及中文输入法问题

### ISSUE THREAD

**Issue by htharoldht** [CoolQ/docker-wine-coolq#28]
本人环境：
>系统：Debian+Docker
>浏览器：火狐（Firefox）
>本机输入法：搜狗拼音输入法

经过测试发现，不能够直接输入中文，因为无相关输入法，本机的输入法不能够直接输入汉字。
另外，尝试使用复制粘贴，发现中文会乱码，如下图所示（使用的是原生的语料库）
![图片](https://user-images.githubusercontent.com/31093493/62869370-53a40b00-bd4a-11e9-8f74-daca64c52197.png)

望解决

**Comment by oott123** [comment]
是有这个问题，现在阶段可以试着在本地搞好，再传文件到服务器上；目前还不太容易修复

**Comment by oott123** [comment]
鉴于上游 https://github.com/novnc/noVNC/pull/1366 已经提出修复方法了，我会在 oott123/novnc 上引入这样的更新，测试没问题后更新到这边来。

**Comment by oott123** [comment]
已经通过 v3.0.0 支持了完整的拼音输入和 Unicode 剪贴板。请尝试如下镜像：

```
docker pull coolq/wine-coolq:v3.0.0
```
