### ISSUE TITLE
下载coolQ 因为网站是http所以被禁止访问

### ISSUE THREAD

**Issue by zlq4863947** [CoolQ/docker-wine-coolq#29]
执行 `wget -O /dev/null http://dlsec.cqp.me/cqa-tuling` 结果:

--2019-08-21 16:35:09--  http://dlsec.cqp.me/cqa-tuling
dlsec.cqp.me (dlsec.cqp.me) をDNSに問いあわせています... 162.159.225.113, 162.159.224.113
dlsec.cqp.me (dlsec.cqp.me)|162.159.225.113|:80 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 403 Forbidden
2019-08-21 16:35:09 エラー 403: Forbidden。

![image](https://user-images.githubusercontent.com/6490251/63412125-01da3f80-c432-11e9-807a-8f825f550592.png)

**Comment by zlq4863947** [comment]
额 地址没有https的吗？

**Comment by oott123** [comment]
增加环境变量

`-e COOLQ_URL="https://dlsec.cqp.me/cqa-tuling"`

**Comment by zlq4863947** [comment]
非常感谢！
