### ISSUE TITLE
VNC_PASSWD无效

### ISSUE THREAD

**Issue by Bpazy** [CoolQ/docker-wine-coolq#3]
```
export VNC_PASSWD='testpwd'
docker run....
```

连接的时候密码依旧是默认的`MAX8char`。
看了dockerfile中依赖的[novnc](https://hub.docker.com/r/oott123/novnc/)的readme，貌似VNC_PASSWD必须要配置在下图中：
![snipaste_2018-01-02_16-46-58](https://user-images.githubusercontent.com/9838749/34478569-90ac128c-efdc-11e7-9f98-47c6ffa7555c.png)

**Comment by oott123** [comment]
请使用 `docker run -e VNC_PASSWD=testpwd` 以将环境变量传递给 docker 容器。

ref: https://docs.docker.com/engine/reference/run/#env-environment-variables
