### ISSUE TITLE
考虑基础镜像使用windows

### ISSUE THREAD

**Issue by liyinanCoder** [CoolQ/docker-wine-coolq#30]
docker hub上有windows的基础镜像，是否考虑使用[windows基础镜像](https://hub.docker.com/_/microsoft-windows?tab=reviews) 和 [RDS](https://withinrafael.com/2018/03/09/using-remote-desktop-services-in-containers/) 来代替 wine

**Comment by oott123** [comment]
本项目旨在使用 Linux 服务器搭建酷Q服务。

由于 Windows 容器需要使用 Windows Server 作为宿主机器，其便捷性甚至不如直接下载酷Q运行，因此暂不考虑。
