### ISSUE TITLE
窗口文字变黑框以及一些建议

### ISSUE THREAD

**Issue by vxray** [CoolQ/docker-wine-coolq#31]
- 问题
打开窗口后复选框说明文字会变成黑框
<img width="702" alt="WX20190903-140436@2x" src="https://user-images.githubusercontent.com/15797571/64147909-73fc4c80-ce54-11e9-8a93-39966ebc757b.png">

- 小小的建议

     可否直接开发原生支持Linux环境的酷Q而不是使用wine呢，既然协议摸清楚了那么应该可以用跨平台语言实现的。那样的话使用API操作应该会流畅很多也能避免兼容性问题。插件开发者可以直接用https api或者websocket进行操作了。

**Comment by oott123** [comment]
你好，黑框的问题属于 wine 的兼容性问题，目前暂时无法修复。

关于酷Q的建议请在官方论坛发表，感谢你的支持。
