### ISSUE TITLE
The GitHub Actions badge is broken

### ISSUE THREAD

**Issue by Coxxs** [CoolQ/docker-wine-coolq#36]
Here's a shiny new badge!
[![Actions Status](https://github.com/CoolQ/docker-wine-coolq/workflows/Build%20and%20Push%20for%20Branches/badge.svg)](https://github.com/CoolQ/docker-wine-coolq/actions)

```
[![Actions Status](https://github.com/CoolQ/docker-wine-coolq/workflows/Build%20and%20Push%20for%20Branches/badge.svg)](https://github.com/CoolQ/docker-wine-coolq/actions)
```

Document: https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

Maybe we need to shorten the workflow name in the `main.workflow` file to make the badge looks better.

**Comment by oott123** [comment]
fell free to make PRs and i will review them

**Comment by Coxxs** [comment]
https://github.com/CoolQ/docker-wine-coolq/commit/5f4236accf9e7900a4b995d295f7d82df8822379
