### ISSUE TITLE
docker中的爱音乐无法使用

### ISSUE THREAD

**Issue by libsgh** [CoolQ/docker-wine-coolq#37]
![image](https://user-images.githubusercontent.com/25656088/64590725-ca303900-d3da-11e9-89ac-7cd8d0ad09bb.png)

尝试了很久只有在docker中有这个问题，在windows上是可以发送音乐的，版本都是最新版。

**Comment by libsgh** [comment]
补充一下，服务器在中国，docker也不行

**Comment by oott123** [comment]
hard to say, 换个别的插件试试
