### ISSUE TITLE
酷Q 5.15.2A开发模式加载插件成功，但是启用插件报错，窗口失去响应

### ISSUE THREAD

**Issue by luffy9412** [CoolQ/docker-wine-coolq#39]
报错信息：
QA.exe: corruntimehost.c:1353：ReallyFixupVTable: 假设 ‘0’ 失败。

**Comment by luffy9412** [comment]
windows系统下同样使用酷Q 5.15.2A，可正常加载、启用插件。

**Comment by oott123** [comment]
非开发者模式正常吗
建议在 win 下开发

**Comment by luffy9412** [comment]
> 非开发者模式正常吗
> 建议在 win 下开发

**Comment by luffy9412** [comment]
> 非开发者模式正常吗
> 建议在 win 下开发

我就是在win10环境下开发的，使用的[c#SDK](https://github.com/Jie2GG/Native.Csharp.Frame)
只是想放到docker 的wine环境下运行。现在是就算用基础模板，不写任何业务逻辑，创建的应用，也是运行不了呢。

**Comment by oott123** [comment]
不支持 C#

**Comment by luffy9412** [comment]
> 不支持 C#
大佬回复好快呀，我才刚刚看到邮件通知的。
我后来想想也是，毕竟系统内核不一样，我打包的时候还是选择的.NET4.5。wine应该是不支持转换高版本的API吧。后来就换成了[coolq-http-api](https://github.com/richardchien/coolq-http-api)，简单粗暴解决linux服务器上部署的问题。

**Comment by Coxxs** [comment]
Wine 不支持 C#
https://appdb.winehq.org/objectManager.php?sClass=version&iId=25478

**Comment by luffy9412** [comment]
> Wine 不支持 C#
> https://appdb.winehq.org/objectManager.php?sClass=version&iId=25478

英语盲人看得费劲，这是wine .NET4.5的测试结果吗，好多BUG啊。
