### ISSUE TITLE
coolQ遇到问题

### ISSUE THREAD

**Issue by xiaotan828** [CoolQ/docker-wine-coolq#4]
![download](https://user-images.githubusercontent.com/33599274/35183344-6c6c6984-fe1f-11e7-945b-e276392c50e7.png)
一开始正常得运行了几分钟，然后突然就这样了

**Comment by oott123** [comment]
请禁用所有插件，尝试检查是否为插件引起。若为插件引起，烦请联系插件作者处理。

**Comment by xiaotan828** [comment]
@oott123 关键现在已经没办法做任何操作了，输完密码MAX8char就这样子，点确定3秒coolq就重启

**Comment by oott123** [comment]
是否安装了插件？是否在插件安装后出现问题？
请在 Linux 端映射的 酷Q 文件夹中删掉所有插件再尝试，或是删除整个 酷Q 文件夹。

**Comment by xiaotan828** [comment]
ok我马上试，不过没装新插件，就是图灵原来自带的四个，开了三个：运行状态，音乐和图灵，不是插件开启后立刻就出问题的，爱音乐也试过给我推了歌，然后过了大概五分钟才出问题

**Comment by oott123** [comment]
如果不是插件问题，这就很奇怪。按说 zlib 不应该有啥毛病，不知道为何会缺失函数。

**Comment by xiaotan828** [comment]
电脑暂时没电了不能删，那我现在该怎么办，主要是空间占用问题，装一个新的是不是意味着double 的空间

**Comment by xiaotan828** [comment]
@oott123 我尝试了一下，是我的putty窗口不能关掉，一关首先docker上不去了，再次启动就会出现如上问题，但是我的电脑不能一直开着啊，并且运行时不能输其他任何命令，怎么解决呢

**Comment by oott123** [comment]
请参考： <https://cqp.cc/t/34558> 以了解更为方便的使用方式。此处留下的说明仅为熟练使用 docker 的用户参考。

**Comment by xiaotan828** [comment]
感谢你，无论如何暂时解决了
