### ISSUE TITLE
阿里云服务器，Ubuntu，无界面，出现验证点击“chrome”无反应,换号出现“”

### ISSUE THREAD

**Issue by BaldStrong** [CoolQ/docker-wine-coolq#40]
阿里云服务器，Ubuntu，无界面，出现验证点击“chrome”无反应,换号出现“开始设备锁才能登录”

**Comment by Coxxs** [comment]
docker 不支持 chrome，可以尝试拒绝验证。如果提示启用设备锁，请启用设备锁。
