### ISSUE TITLE
VNC 无法登陆，提示无法连接到服务器！

### ISSUE THREAD

**Issue by leonGravel** [CoolQ/docker-wine-coolq#47]
使用
```
docker run --name=coolq -d -p 8080:9000  -v /root/dockerDir/coolQ:/home/user/coolq -e VNC_PASSWD=12345678 -e COOLQ_ACCOUNT=6666 coolq/wine-coolq
```
启动镜像之后，`logs` 无报错情况。但是本地连接到 `localhost:9000` 之后，输入密码，让我确认了酷Q的用户使用协议之后，点击确认。
提示下面这个错误。 
<img width="568" alt="QQ20200126-143117@2x" src="https://user-images.githubusercontent.com/13548712/73131581-8f0c6a80-4048-11ea-9b66-c17cfac26521.png">

使用 `docker run --rm coolq/wine-coolq curl myip.ipip.net` 测试网络没有问题。

本机情况：
 macOS 10.15.2
 docker Version: 19.03.5

**Comment by oott123** [comment]
这是酷Q的问题，应当在用户论坛提问。

**Comment by leonGravel** [comment]
> 这是酷Q的问题，应当在用户论坛提问。

好的，已在社区提问，https://cqp.cc/t/46752 ，不过问题需要审核，烦请大佬在社区解答一下 😄

**Comment by oott123** [comment]
有审核的帖子我看不了；此外关于这个问题我也解答不了（不属于我的能力和职责范围），因此还是希望你在社区寻求支持。这个 issue 我先 close 啦。

**Comment by 2793145003** [comment]
您好，我遇到了同样的问题。
然后在VNC中运行wine CQA.exe，发现好像是wine的锅。
![image](https://user-images.githubusercontent.com/24595900/73468953-91602300-43c0-11ea-8cb0-e70b3b5ad22f.png)

**Comment by oott123** [comment]
@2793145003 你好，这个仓库只处理诸如无法启动、无法展示登录框等问题。登录出现 CA999 是酷Q方面的问题，我无法处理解答，请到社区反馈。

**Comment by 2793145003** [comment]
解决了。
要先ls -list查看一下挂载文件夹的权限与所有者。
因为如果在mac中直接从终端mkdir的话，文件夹的所有者可能是root，于是在docker里面没有挂载路径的修改权限。
直接把文件夹rm了用改访达建就行了。

**Comment by oott123** [comment]
@2793145003 你好，谢谢你的反馈。我这边后续看看能不能检查一下权限。
@leonGravel 可以试试 https://github.com/CoolQ/docker-wine-coolq/issues/47#issuecomment-580699635 的这个方法能否解决你的问题。

**Comment by leonGravel** [comment]
@oott123 貌似不行，我这边docker能够正常挂载文件的。使用访达创建文件夹之后，再次尝试。依然不行。
然后：
我进入docker容器。
```
docker exec -it coolq /bin/bash

cd /home/user/coolq
 
wine CQA.exe

```
日志如下：
```
0009:fixme:heap:RtlSetHeapInformation 0x650000 0 0x33fe3c 4 stub
0009:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0009:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0009:fixme:msscript:ScriptControl_QueryInterface (0x111fd8)->({00000126-0000-0000-c000-000000000046} 0x33fc78)
0009:fixme:msscript:ActiveScriptSite_OnStateChange (0x131598, 5)
0009:fixme:msscript:ScriptControl_Eval (0x111fd8)->(L"1+1" 0x33fb08)
002a:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002a:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
root@ffe53af12552:/home/user/coolq# 002a:err:winebrowser:wmain Usage: winebrowser URL

```

好像什么都没有发生，没有报错，也没有登录界面。
另外我在novnc的界面依然提示，无法连接到服务器。
