### ISSUE TITLE
插件里的功能有些用不了，比如@某人的指令，以及带阿拉伯数字的指令

### ISSUE THREAD

**Issue by wdmhydw** [CoolQ/docker-wine-coolq#50]
试了很多插件，在win上没问题，但在服务器上就会显示指令错误，只要带有阿拉伯数字
![QQ截图20200306001751](https://user-images.githubusercontent.com/61841146/76001358-f23ec600-5f3f-11ea-9206-5b2bae2b8a99.png)上面的是在win运行，下面的是在服务器运行，相同的指令

**Comment by oott123** [comment]
wine 不保证插件能用，插件不兼容请改用 Windows
