### ISSUE TITLE
使用Docker on Raspbian在树莓派上创建酷Q容器报错：exec format error

### ISSUE THREAD

**Issue by HaloSense** [CoolQ/docker-wine-coolq#52]
除了每一句都加了个sudo之外，我每一步都是按照教程操作的，但是在创建容器的时候会提示
`standard_init_linux.go:211: exec user process caused "exec format error"`
本人不是专业学这个的，还请大佬解答

**Comment by oott123** [comment]
不支持树莓派

**Comment by Coxxs** [comment]
#24
