### ISSUE TITLE
在wine下运行爆错

### ISSUE THREAD

**Issue by IPlayForHer** [CoolQ/docker-wine-coolq#6]
![image](https://user-images.githubusercontent.com/21272351/38180964-8fea8724-3673-11e8-9eb5-776d9e74f509.png)
在wine下运行爆错

**Comment by Coxxs** [comment]
请提供具体错误信息及截图

**Comment by Coxxs** [comment]
感谢反馈，这应该是应用兼容性问题，建议联系应用作者，或在 Windows 系统下运行。

    https://cqp.cc/t/34558
    由于 wine 技术原理为 Windows 系统，实现与原生系统尚有差距，部分应用运行或有兼容性问题。
